/*
   Program to return all the subsequence of a string.
   A String is a subsequence of a given String, that is generated by deleting
   some character of a given string without changing its order.
 */

#include <cmath>
#include <iostream>
using namespace std;

int subs(string input, string output[]) { //Output array of string
    if (input.empty()) {                  //input.size()
        output[0] = "";                   // empty string
        return 1;                         // 1 subsequence
    }
    string smallString = input.substr(1);
    int smallOutputSize = subs(smallString, output);
    for (int i = 0; i < smallOutputSize; i++) {
        output[i + smallOutputSize] = input[0] + output[i];
    }
    return 2 * smallOutputSize;
}

int main() {
    string input;
    cin >> input;
    int size = pow(2, input.length());
    string *output = new string[size];
    int count = subs(input, output);
    for (int i = 0; i < count; i++) {
        cout << output[i] << endl;
    }
}

/*
   abcd

   d
   c
   cd
   b
   bd
   bc
   bcd
   a
   ad
   ac
   acd
   ab
   abd
   abc
   abcd
 */

/*
   string size is n then it will have 2^n substring.
   Beacause for every letter we have 2 decision to take wheather to take it or not.
 */
